name: Keep E5 Alive

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 00:00 UTC（北京时间 08:00）
    - cron: '0 12 * * *'  # 每天 12:00 UTC（北京时间 20:00）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run keep-alive script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python keep-alive.py
